# Generated by Django 2.2.1 on 2019-05-11 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='documentCode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
