# Generated by Django 2.2.1 on 2019-05-12 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0003_lead_documentcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='documentStageCode',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
