# Generated by Django 2.2.1 on 2019-05-14 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_auto_20190513_2155'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='noteText',
            field=models.CharField(blank=True, max_length=500),
        ),
    ]
